steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: '/opt/sap/mta.jar'
  neoDeploy:
    neoHome: '/opt/sap/neo-sdk/'
    neo:
      credentialsId: 'NEO_DEPLOY'
      account: 'lak5j2nw8w'
      host: 'eu1.hana.ondemand.com'
