steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: '/home/osboxes/mta_archive_builder.jar'
  neoDeploy:
    neoHome: '/home/osboxes/NEO-java-web-sdk/tools'
    neo:
      credentialsId: 'NEO_DEPLOY'
      account: 'lak5j2nw8w'
      host: 'eu1.hana.ondemand.com'
